[project]
name = '100daysofclarity'
description = ''
authors = []
telemetry = true
cache_dir = '.cache'
requirements = []
[contracts.artist-discography]
path = 'contracts/artist-discography.clar'
clarity_version = 2
epoch = 2.5

[contracts.clarity-basics-i]
path = 'contracts/clarity-basics-i.clar'
clarity_version = 1
epoch = 2.05

[contracts.clarity-basics-ii]
path = 'contracts/clarity-basics-ii.clar'
clarity_version = 1
epoch = 2.05

[contracts.clarity-basics-iii]
path = 'contracts/clarity-basics-iii.clar'
clarity_version = 2
epoch = 2.5

[contracts.clarity-basics-iv]
path = 'contracts/clarity-basics-iv.clar'
clarity_version = 2
epoch = 2.5

[contracts.community-hello-world]
path = 'contracts/community-hello-world.clar'
clarity_version = 2
epoch = 2.5



[contracts.offspring-will]
path = 'contracts/offspring-will.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
